### ISSUE TITLE
IE vs Chrome

### ISSUE THREAD

**Issue by bobrinch** [glinscott/Garbochess-JS#16]
Hi

I have discovered what seems to be a problem with GarboChess UI running in IE, when computer has to do a simple mate. For example try to preload this FEN into GarboChess UI in IE:

8/5q2/8/k7/8/3K4/8/8 w - -

It will take forever for computer to mate, while it goes fast in Chrome.

I use IE 10 and Chrome 27.x.

Could you please look into the reason for this.

Best regards
Bo.

**Comment by casaschi** [comment]
I believe it depends on the speed of the javascript engine of each browser.
IE is just slower than Chrome, nothing for Garbochess to fix here I'm afraid.

**Comment by glinscott** [comment]
Yes, unfortunately, nothing much to be done here.  IE is still quite a lot slower than chrome.
