### ISSUE TITLE
Dies in Firefox after 20 moves

### ISSUE THREAD

**Issue by FrankWST** [glinscott/Garbochess-JS#5]
The engine doesn't answer after about 15 or 20 moves in Firefox. The game doesn't continue.

**Comment by glinscott** [comment]
Which version of Firefox are you running?

**Comment by FrankWST** [comment]
I use the lates version 8.0 of Firefox.

**Comment by glinscott** [comment]
Ok, thanks, I'll check it out.

**Comment by FrankWST** [comment]
Could you reproduce the behaviour?

**Comment by glinscott** [comment]
Sorry for the delay.  Haven't been able to reproduce it no.  I was able to play this game in Firefox 9 without any difficulty.

Can you reproduce it reliably?  What error do you see in the javascript console?
1. e4 d5 2. exd5 Qxd5 3. Nc3 Qd6 4. Nf3 Nf6 5. Bc4 Be6 6. Bb3 Nc6 7. d3 Nd4 8. O-O Ng4 9. g3 Nxb3 10. axb3 Nf6 11. Bf4 Qd7 12. Ne5 Qd8 13. Qf3 c6 14. Ra4 a5 15. Rfa1 h6 16. Qe3 g5 17. Bxg5 hxg5 18. Qxg5 Rh5 19. Qe3 Bh6 20. Qc5 Nd7 21. Nxc6 Nxc5 22. Nxd8 Rxd8 23. Rxa5 Bg7 24. b4 b6 25. Ra7 Nd7 26. Ne4 Bxb2 27. R1a2 Bxa2 28. Rxa2 Be5

**Comment by FrankWST** [comment]
No problem in FF 9.

**Comment by glinscott** [comment]
Great, glad to hear.
